#!/bin/bash

if [ "$UID" != "0" ]; then
   echo "Logue como administrador..."
   exit
fi

while sleep 2s; do
   echo "Criando backup... $(date +%d%m%Y)"
   tar -cz -v /home >/var/backup/home$(date +%d%m%Y).tar.gz
done
